### ISSUE TITLE
Perform 301 to https:// for initial request

### ISSUE THREAD

**Issue by JustinBeckwith** [helmetjs/hsts#17]
If it's the first time the browser has seen a url, it will serve over http:// even if you send all the correct HSTS headers.  The user has to hit it over https:// at least once before HSTS wakes up and starts forcing SSL. Would it be possible to bake the 301 for the first request in?

**Comment by EvanHahn** [comment]
This is a good idea, but not this module's responsibility. [express-enforces-ssl](https://github.com/aredo/express-enforces-ssl) does this.

I'll make sure the documentation reflects this more clearly and then I'll close this issue.

**Comment by EvanHahn** [comment]
Added this to the readme and the docs.

Thanks for reminding me to "promote" this in the documentation!
