### ISSUE TITLE
Be HSTS-Preload friendly out of the box

### ISSUE THREAD

**Issue by na-n** [helmetjs/hsts#27]
Hi :)

I'm using ExpressJS with HelmetJS behind NGINX. Helmet controls _most_ of the headers.

I'm using `app.use(helmet());`

According to `https://hstspreload.org/?domain=<my-domain-here>`:

![image](https://user-images.githubusercontent.com/15941240/59377272-c17f8680-8d49-11e9-80fe-8af80f780807.png)

I think setting the default maxAge to 1yr and setting preload to default as true would make adoption of HSTS preload a lot easier throughout the web - especially for ExpressJS users like myself :smile: .

Is it reasonable to ask?

Amazing project, by the way.

**Comment by EvanHahn** [comment]
I believe the `preload` option is exactly what you're looking for:

```js
app.use(hsts({
  maxAge: 31536000,        // Must be at least 1 year to be approved
  includeSubDomains: true, // Must be enabled to be approved
  preload: true
}))
```

Does that help?

**Comment by na-n** [comment]
I'm hoping to be able to use 
```
app.use(helmet({
  hsts: {
    includeSubDomains: true,
    preload: true,
    maxAge: 31536000
  }
}));
```

.. I'm not going to turn anything off am I?
The little documentation is a teeeeny bit unclear to my probably-pedant mind (admittedly, Helmets docs):
![image](https://user-images.githubusercontent.com/15941240/59380777-c2b4b180-8d51-11e9-8167-6e7e2bba6c93.png)

**Comment by na-n** [comment]
OK I tried `curl -v` and saw that everything was fine with the code change indicated above.
I'm new at this!

Your suggestion/my augmentation are what I was looking for. :smile:

**Comment by EvanHahn** [comment]
Great! Let me know if I can help with anything else.
