### ISSUE TITLE
Can't get HSTS to work with Koa

### ISSUE THREAD

**Issue by felixsanz** [helmetjs/hsts#9]
I don't know what i'm doing wrong, but please someone point me it!

I'm using:

```javascript
  server.use(helmet({
    hsts: {
      maxAge: 10886400000,
      includeSubDomains: true,
      preload: true,
      force: true,
    },
  }))
```

My site is only served in HTTPS. But still the header is not there. Why?

**Comment by EvanHahn** [comment]
Are you using the [koa-helmet package](https://github.com/venables/koa-helmet)? If not, try switching to that to see if this works. If you _are_ using koa-helmet, could you report the issue there and see if they can help you?

**Comment by felixsanz** [comment]
Yea, i'm using koa-helmet. But koa-helmet is just a wrapper for helmet. Is just promisify this module, nothing else

**Comment by felixsanz** [comment]
If it helps, all other modules works fine:

```
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Download-Options: noopen
X-XSS-Protection: 1; mode=block
```

etc

**Comment by EvanHahn** [comment]
Could https://github.com/venables/koa-helmet/issues/18 be related?

**Comment by EvanHahn** [comment]
Sorry I'm not more helpful here—I'm traveling! I can take a further look when I return.

**Comment by felixsanz** [comment]
I'm using `force: true` so i don't think my problem relates to #18 :(

**Comment by EvanHahn** [comment]
Could you try a simple example with Express instead of Koa? That will help determine where the problem is.

I can try it when I'm back at a laptop, but that might be awhile. Sorry!

**Comment by felixsanz** [comment]
An express app returns this:

```
HTTP/1.1 200 OK
X-DNS-Prefetch-Control: off
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=10886400; includeSubDomains; preload
X-Download-Options: noopen
X-XSS-Protection: 1; mode=block
Content-Type: text/html; charset=utf-8
Content-Length: 12
ETag: W/"c-7Qdih1MuhjZehB6Sv8UNjA"
Date: Wed, 06 Jul 2016 14:32:47 GMT
Connection: keep-alive
```

while the same app using koa and koa-helmet returns this:

```
HTTP/1.1 200 OK
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Download-Options: noopen
X-XSS-Protection: 1; mode=block
Content-Type: text/plain; charset=utf-8
Content-Length: 11
Date: Wed, 06 Jul 2016 14:38:42 GMT
Connection: keep-alive
```

Lot of differences :/

**Comment by felixsanz** [comment]
But remember that koa-helmet is just a wrapper to promisify helmet. Options are passed directly to helmet. I don't think koa-helmet can fix this. Probably this is an issue with helmet and the `ctx` object that is passed (req, res)

**Comment by EvanHahn** [comment]
Hmm. I'll take a look when I get a chance (though it may be a bit due to travel and other things).

**Comment by EvanHahn** [comment]
Instead of this:

```javascript
server.use(helmet({
  hsts: {
    maxAge: 10886400000,
    includeSubDomains: true,
    preload: true,
    force: true,
  },
}))
```

Could you try this?

```javascript
server.use(helmet.hsts({
  maxAge: 10886400000,
  includeSubDomains: true,
  preload: true,
  force: true,
}))
```

This will _only_ use the HSTS part of Helmet. Do you see the header there when you do that?

**Comment by felixsanz** [comment]
Yes, it works:

```
HTTP/1.1 200 OK
Vary: Accept-Encoding
Strict-Transport-Security: max-age=10886400; includeSubDomains; preload
Set-Cookie: cookieeu=true; path=/; expires=Wed, 12 Jul 2017 19:39:59 GMT; secure; httponly
Content-Type: text/html; charset=utf-8
Content-Length: 12438
Date: Tue, 12 Jul 2016 19:39:59 GMT
Connection: keep-alive
```

Any idea why? I would like to just use `helmet` instead of all packages separately! :stuck_out_tongue_closed_eyes:

**Comment by EvanHahn** [comment]
Still unsure, but this is beginning to seem like an issue with `koa-helmet` (or maybe a problem with Helmet that makes it more difficult to interface with).

Some things to try:

1. `koa-helmet@2.0.0` was recently released. Have you upgraded?
1. Could you look at the source code for `koa-helmet` to see if there's anything fishy in there?
1. For now, you might be able to do something like this as a workaround:

    ```javascript
    server.use(helmet())

    server.use(helmet.hsts({
      maxAge: 10886400000,
      includeSubDomains: true,
      preload: true,
      force: true,
    }))
    ```

**Comment by felixsanz** [comment]
I was using **2.0.0-alpha1** and the problem was there. But now i upgraded to stable **2.0.0** (since he bumped the helmet version few days ago because [i requested it](https://github.com/venables/koa-helmet/issues/21) in the issue tracker, and now it's fixed.

Sorry for wasting your time. I think the problem was that 2.0.0-alpha1 was using helmet 1.x and 2.0.0 is using helmet 2.x.

Thanks! Fixed

**Comment by EvanHahn** [comment]
Glad you figured it out!
